-- ! this is just a file to put things that no longer are being used, but still
-- worked well to consider switching back to in the future.



-- !! CMP !!

-- just in case copilot gets fussy, here's the original snippet:
-- ['<Tab>'] = cmp.mapping(function(fallback)
--   if cmp.visible() then
--     cmp.select_next_item()
--   elseif luasnip.expand_or_jumpable() then
--     luasnip.expand_or_jump()
--   else
--     fallback()
--   end
-- end, { 'i', 's' }),

-- formatting = {
--   -- show import path or library name
--   format = function(entry, vim_item)
--     vim_item.kind = require('lspkind').presets.default[vim_item.kind]
--     vim_item.menu = ({
--       nvim_lsp = '',
--       luasnip = '﬌',
--       buffer = '﬘',
--       path = '',
--     })[entry.source.name]
--     return vim_item
--   end,
-- }

--  formatting = {
--   format = function(entry, vim_item)
--     vim_item.kind = require('lspkind').presets.default[vim_item.kind]
--     vim_item.menu = ({
--       nvim_lsp = '[LSP]',
--       buffer = '[BUF]',
--       luasnip = '[SNIP]',
--       path = '[PATH]',
--     })[entry.source.name]
--     return vim_item
--   end,
-- },

-- formatting = { -- this doesnt work for some reason. plz, someone tell me how to get the icons to show up in the completion menu
--   fields = { 'menu', 'abbr', 'kind' },
--   format = function(entry, item)
--     local menu_icon = {
--       nvim_lsp = 'λ',
--       path = '🖫',
--       luasnip = '⋗',
--       buffer = 'Ω',
--     }
--     item.menu = menu_icon[entry.source.name]
--     return item
--   end,
-- }
--
--
--
--
-- formatting = {
--   fields = { 'menu', 'abbr', 'kind' },
--   format = require('lspkind').cmp_format({
--     menu = ({
--       nvim_lsp = '',
--       luasnip = '﬌',
--       buffer = '﬘',
--       path = '[PATH]',
--       -- path = '',
--     }),
--     -- with_text = true,
--     -- mode = 'symbol',
--     -- maxwidth = 100,
--     -- ellipsis_char = '...',
--   })
-- }
-- !! CMP !!
