--- this is for the material theme, when i wanna use it
-- -- these set the ported VSC community material color theme
-- -- and adjust the colors for specific elements to match the vscode version
-- vim.cmd 'colorscheme material'
-- vim.cmd 'highlight Identifier guifg=#eeffff'
-- vim.cmd 'highlight keyword guifg=#c792ea'
-- -- ...because i like it....
